# Generated by Django 5.0.7 on 2024-07-20 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citysearch',
            unique_together={('user', 'city_name')},
        ),
    ]
